### ISSUE TITLE
Adding bracket to line 508 - main.py

### ISSUE THREAD

**Issue by ksoju** [ekknod/scripthial#1]
Hello, main.py line 508 should have brackets to avoid a potential div/0 error. I'm on mobile so can't properly paste the line change. Cheers!

edit: kind of new to github, sorry if I'm not following programming etiquette.
Here's what I mean... 

`radius = 1.0 / math.sqrt(vec.x * vec.x + vec.y * vec.y + vec.z * vec.z) + 1.192092896e-07`
`radius = 1.0 / (math.sqrt(vec.x * vec.x + vec.y * vec.y + vec.z * vec.z) + 1.192092896e-07)`

**Comment by ekknod** [comment]
https://github.com/ekknod/scripthial/commit/10816601e9ca503263962918dbda21550c607a6a
thx! :)
