### ISSUE TITLE
Error: Interface [VClient] not found!

### ISSUE THREAD

**Issue by onefckcps** [ekknod/scripthial#11]
Hey, i think they not only updated the client_panorama...i got this error

Error: Interface [VClient] not found!

**Comment by miguelshta21** [comment]
same here

**Comment by miguelshta21** [comment]
any fix?

**Comment by ssstylish** [comment]
When using the linux script i get error: Error: Interface [VClient] not found!
Any tip how I can bypass this by changing the code?

**Comment by ekknod** [comment]
@onefckcps i will fix it august

**Comment by ekknod** [comment]
Fixed. Enjoy guys
