### ISSUE TITLE
ESP does not work in the most recent update

### ISSUE THREAD

**Issue by AuriumWorld** [ekknod/scripthial#21]

**Comment by Levick13** [comment]
pls update health esp

**Comment by ksoju** [comment]
`index = mem.read_i32(entity.address + nv.m_iGlowIndex) * 0x38          ## replace 0x38 with new size of glow struct
mem.write_float(glow_pointer + index + 0x04, 1.0 - entity_health)  # r ## replace 0x04 with new offset value
mem.write_float(glow_pointer + index + 0x08, entity_health)        # g ## replace 0x08 with new offset value 
mem.write_float(glow_pointer + index + 0x0C, 0.0)                  # b ## replace 0x0C with new offset value
mem.write_float(glow_pointer + index + 0x10, 0.8)                  # a ## replace 0x10 with new offset value
mem.write_i8(glow_pointer + index + 0x24, 1)                           ## replace 0x24 with new offset value
mem.write_i8(glow_pointer + index + 0x25, 0)                           ## replace 0x25 with new offset value`

**Comment by ksoju** [comment]
index = mem.read_i32(entity.address + nv.m_iGlowIndex) * 0x38
mem.write_float(glow_pointer + index + 0x08, 1.0 - entity_health)  # r
mem.write_float(glow_pointer + index + 0x0C, entity_health)        # g
mem.write_float(glow_pointer + index + 0x10, 0.0)                  # b
mem.write_float(glow_pointer + index + 0x14, 0.8)                  # a
mem.write_i8(glow_pointer + index + 0x28, 1)
mem.write_i8(glow_pointer + index + 0x29, 0)

**Comment by st1650** [comment]
Absolutely based. Great job.

**Comment by KAOSYEET** [comment]
for some reason it not work for me, when i try execute its just popup python 1 sec, then shut down

**Comment by st1650** [comment]
Will need an update ...
