### ISSUE TITLE
Removed glow in new linux commit?

### ISSUE THREAD

**Issue by AuriumWorld** [ekknod/scripthial#27]
Not sure if this was on purpose but glow does not currently work in linux and I noticed the g_glow was removed. was this intentional?

**Comment by ksoju** [comment]
Pattern for linux is probably out of date, but noticed from tuxdump that their config was updated. I can't confirm it will work myself though.

[https://github.com/Teklad/tuxdump/blob/master/config/csgo.cfg#L251](url)
