### ISSUE TITLE
Triggerbot not working any more after today update

### ISSUE THREAD

**Issue by galaxysyed** [ekknod/scripthial#31]

**Comment by dev5tar** [comment]
something changed regarding input? offset? hazedumper it outdated. UC doesnt show offsets in this format.

**Comment by galaxysyed** [comment]
Nothing changed... Can't say anything about offsets. But triggerbot was working until yesterday. But after the update, the triggerbot is not working but the walls are still showing up.

Any kind of help would be appreciated.

**Comment by fleesu** [comment]
Hi

Also having problems. I've my own version of this and noticed it stopped working. I did some debugging and found out that the script always stops on the check `if engine.is_in_game():` (scripthial_windows.py L614). I tried printing it and its value is always "0", in public games or bot games, no matter if I use the -insecure tag.

**Comment by dev5tar** [comment]
dwinput dwclientstate, so much changed its beyond the auto update capability.

**Comment by galaxysyed** [comment]
Sad, And @ekknod  is not there since 2 months. 
So there will be no fix right?
