### ISSUE TITLE
Script doesn’t pass is_in_game() check

### ISSUE THREAD

**Issue by fleesu** [ekknod/scripthial#33]
Hi

Not sure if I should make an issue or not because other’s already have. 

A quote of my comment on another issue:

> Also having problems. I've my own version of this and noticed it stopped working. I did some debugging and found out that the script always stops on the check if engine.is_in_game(): (scripthial_windows.py L614). I tried printing it and its value is always "0", in public games or bot games, no matter if I use the -insecure tag.

> I'm guessing it's something with dwClientState? Because stuff like localplayer's team num also gives me 0 for a value

**Comment by dev5tar** [comment]
Lots changed and it doesnt look like well be seeing an update;
check the follow thread on [UC](https://www.unknowncheats.me/forum/cs-go-releases/353550-windows-linux-aimbot-triggerbot-autoupdate-22.html?posted=1#post3320418)

**Comment by ksoju** [comment]
I just tested G37OBS for a pull request and it works fine. Your issue with clientstate can be addressed by comparing the code:
`function is_in_game()
    return mem_read_i8(m_dwClientState + m_dwState) == 6
end`
vs. python:
`    @staticmethod
    def is_in_game():
        return mem.read_i8(nv.dwClientState + nv.dwState) >> 2`
So one is a bit shift test and the other is an equality test. Whether this fixes it or not, I don't know. If it works put in a pull request.
