### ISSUE TITLE
detectable in linux? vac save?

### ISSUE THREAD

**Issue by Clasoheld** [ekknod/scripthial#7]
hey,
i have added some features to make it better for my use, which is what i actually mean by good work.
But now I was wondering if Steam can detect if this Python script reads memory when I run it with root? I have little experience with game cheats/anti cheats especially on Linux

**Comment by ekknod** [comment]
Hi, sorry for late answer.
It should be VAC undetectable in linux, because vac can't access that cheat.
Only features can be detected, so don't patch .text section and you're safe.
